version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testing
    networks:
      - net
    ports:
      - "3306:3306"

  java-app:
    image: project
    container_name: app
    depends_on:
      - mysql
    networks:
      - net
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testing
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update # or 'create' depending on your needs
      SPRING_JPA_SHOW-SQL: true

networks:
  net:
    driver: bridge
